version: "3.7"

services:
  frontend:
    build:
      context: ..  
      # Utilize "Dockerfile_local" para desenvolvimento (com live-reload/debug) ou "Dockerfile" para produção
      dockerfile: Dockerfile_local
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
